# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

####################
## Mod Information
####################
mod_version = 0.1.0-alpha
mod_authors = nivthefox
mod_group = org.sosly.ecotale
mod_id = ecotale
mod_name = EcoTale
mod_license = MIT
mod_credits = Thanks to my wife anomalagous for her unwavering support, and to Klei_Wright for his amazing inspirational youtube video https://youtu.be/f21YJ5pjPog.
mod_description = EcoTale reimagines Minecraft's ecology, inviting players to cultivate living ecosystems where intuitive, humane choices unlock the richest rewards. Minecraft's creatures have been transformed into dynamic partners with their own behaviors, needs, and gifts for those who tend to them thoughtfully.
mod_logo = ecotale.png

####################
## Core Configuration
###################
minecraft_version = 1.20.1
minecraft_version_range = [1.20.1,)
api_name = forge
api_version = 47.1.100
api_version_range = [47.1,48)
loader_version_range = [2,)
mappings_channel = parchment
mappings_version = 2023.09.03-1.20.1

####################
## Optional Dependencies
###################
jei_projectId = 238222
jei_fileId = 5074448
journeymap_projectId = 32274
journeymap_fileId = 4873863

####################
## Deployment Configuration
###################
# Replace these with your actual project IDs when you register your mod
curseforge_project_id = YOUR_PROJECT_ID
modrinth_project_id = YOUR_PROJECT_ID
